### ISSUE TITLE
Will the repo support Simsiam in the future?

### ISSUE THREAD

**Issue by Epiphqny** [facebookresearch/vissl#159]
Awesome work! Will the Simsiam be supported in the future?

**Comment by prigoyal** [comment]
Hi @Epiphqny , thank you so much! We fully intend to support Simsiam (or any self-supervised method) and welcome contributions. :) We won't be able to release SimSiam immediately and encourage community contributions for faster availability!

**Comment by prigoyal** [comment]
Closing this issue and please track https://github.com/facebookresearch/vissl/issues/191 for progress on this . :)
