### ISSUE TITLE
Pre-release announcement: Implementing vision transformers in vissl

### ISSUE THREAD

**Issue by growlix** [facebookresearch/vissl#186]
# 🌟 Vision transformers are coming to vissl

## Approach description

Transformers have recently demonstrated promising results for visions tasks in supervised contexts ([Dosovitskiy et al., 2020](https://arxiv.org/abs/2010.11929), [Touvron et al., 2020](https://arxiv.org/abs/2012.12877)). We are currently working with the [ClassyVision](https://classyvision.ai/) team to carry forward their vision transformers into vissl.

## Open source status

The implementation is currently underway and we plan to release in the next week. @vedanuj and I (@growlix) are working with @mannatsingh and @anmolkalia from the ClassyVision team.

**Comment by prigoyal** [comment]
https://github.com/facebookresearch/vissl/pull/195

**Comment by prigoyal** [comment]
PR has been merged! closing this issue! thank you @growlix :)
