### ISSUE TITLE
Custom Dataset

### ISSUE THREAD

**Issue by Zumbalamambo** [facebookresearch/vissl#197]
I would like to train SimCLR. How do I prepare the custom dataset? How should I format the dataset ?

**Comment by QuentinDuval** [comment]
Hi Zumbalamanbo,

I will try to answer you as completely as possible. Please feel free to ask for more details if I forgot some. I will first answer the SimCLR part, and then the custom dataset part of your question.

First of all, regarding SimCLR, VISSL allows you to train SimCLR by using the following configuration file: configs/config/pretrain/simclr/simclr_8node_resnet.yaml.

For instance, you can use the following command to train SimCLR on SLURM:

```
python tools/run_distributed_engines.py config=pretrain/simclr/simclr_8node_resnet \
    config.SLURM.USE_SLURM=true \
    config.SLURM.PARTITION=<your_slurm_partition> \
    config.SLURM.NAME=<job_name_on_slurm> \
    config.SLURM.LOG_FOLDER=<folder_where_to_put_the_logs>
```

Now, for the second part, VISSL also allows you to plug your custom datasets by having them in the `disk_folder` format. This is a 3-step process.

**First step** is to have your dataset follow the `disk_folder` format. This format looks like the following (Note that for SimCLR, you will not need the "val" folder):

```
/path/to/your/dataset/
   train/
      label1/
         image1.jpg
         image2.jpg
         ...
     label2/
        ... more images ...
   val/
      label1/
         image1.jpg
         image2.jpg
         ...
     label2/
        ... more images ...
```

**Second step**: Once your dataset has that form, plug it into `configs/config/dataset_catalog.json` to register its location. For instance:

```
  "custom_data_set": {
      "train": ["/path/to/your/dataset/train", "<lbl_path>"],
      "val": ["/path/to/your/dataset/val", "<lbl_path>"]
  },
```

**Third step** is to run your job by customizing the launch command of SimCLR to use your own dataset. In your case, the command would look like this (taking the same command as before but replacing the dataset):

```
python tools/run_distributed_engines.py config=pretrain/simclr/simclr_8node_resnet \
    config.SLURM.USE_SLURM=true \
    config.SLURM.PARTITION=<your_slurm_partition> \
    config.SLURM.NAME=<job_name_on_slurm> \
    config.SLURM.LOG_FOLDER=<folder_where_to_put_the_logs> \
    config.DATA.TRAIN.DATASET_NAMES=[custom_data_set]
```

(Note that you might also need to overload other values if you want for instance to change the transformation pipeline to adapt it to your custom dataset)

**Comment by Zumbalamambo** [comment]
thank you very much!

**Comment by pranay-ar** [comment]
Hi, I am confused as to what would be the kind of file for labels be in "<lbl_path>." Is it a .csv file with the file path corresponding to its labels or is it something else?

**Comment by mominsiddiqui** [comment]
Hi! I followed the steps you have shared but got an error. I'm unable to debug it. What steps would you recommend?

`KeyError: "Dataset 'imagenet1k_filelist' is not registered! Available datasets are: airstore_imagenet, imagenet1k_folder, imagenet_a_filelist, imagenet_r_filelist, imagenette_160_folder, places205_folder, places365_folder, CIFAR10, CIFAR100, STL10, MNIST, SVHN, inaturalist2018_filelist, yfcc100m, aircrafts_folder, caltech101_folder, clevr_count_filelist, clevr_dist_filelist, dsprites_loc_folder, dsprites_orient_folder, dtd_folder, euro_sat_folder, food101_folder, gtsrb_folder, kitti_dist_folder, oxford_flowers_folder, oxford_pets_folder, pcam_folder, small_norb_azimuth_folder, small_norb_elevation_folder, stanford_cars_folder, sun397_filelist, ucf101_folder, kinetics700_frames_folder, coco_folder, imagenet1k-per01, imagenet1k-per10, google-imagenet1k-per01, google-imagenet1k-per10, custom_data_set"KeyError: "Dataset 'imagenet1k_filelist' is not registered! Available datasets are: airstore_imagenet, imagenet1k_folder, imagenet_a_filelist, imagenet_r_filelist, imagenette_160_folder, places205_folder, places365_folder, CIFAR10, CIFAR100, STL10, MNIST, SVHN, inaturalist2018_filelist, yfcc100m, aircrafts_folder, caltech101_folder, clevr_count_filelist, clevr_dist_filelist, dsprites_loc_folder, dsprites_orient_folder, dtd_folder, euro_sat_folder, food101_folder, gtsrb_folder, kitti_dist_folder, oxford_flowers_folder, oxford_pets_folder, pcam_folder, small_norb_azimuth_folder, small_norb_elevation_folder, stanford_cars_folder, sun397_filelist, ucf101_folder, kinetics700_frames_folder, coco_folder, imagenet1k-per01, imagenet1k-per10, google-imagenet1k-per01, google-imagenet1k-per10, custom_data_set"`
