### ISSUE TITLE
Can the framework be adapted for other tasks?

### ISSUE THREAD

**Issue by listener17** [facebookresearch/vissl#227]
## 📚 VISSL Documentation

A clear and concise description of what content in the [Docs](https://github.com/facebookresearch/vissl/tree/master/docs) is an issue.

Not sure if this is the right place to ask this (apologies for that). 

Is VISSL framework a genereic framework? Meaning, can we make use of our models (meant for speech/Audio) and leverage the  VISSL library for SSL?

Currently, I don't see in the documentation or an example of how to adapt the toolbox for non-computer vision work.

**Comment by QuentinDuval** [comment]
Hi @listener17 !

I am not the one handling the roadmap for VISSL (so I will let Priya confirm of infirm what I am saying), but to my knowledge VISSL stands for VIsion SSL and it is geared toward Vision only.

There might be a space for reusing some of the parts of VISSL for other modalities (like speech, etc.), for instance, parts algorithms like SimCLR might work cross-modalities (like image embeddings vs text embedding) but to my knowledge this is not in the DNA of VISSL.

**Comment by prigoyal** [comment]
thank you @listener17 , adding to what @QuentinDuval shared: VISSL has indeed been used for other purposes including audio, text modalities. However, we have not officially supported the other modalities and released code in VISSL yet. 

We do welcome your contributions / proposals though.

**Comment by listener17** [comment]
Thanks @prigoyal and @QuentinDuval that answers my questions. 
Being an audio guy, I will keep an eye on VISSL and maybe play with it during spare time to get better feeling. 

Thanks for the good work!
