### ISSUE TITLE
Wrong package apex gets installed while following the documentation

### ISSUE THREAD

**Issue by rhomu** [facebookresearch/vissl#233]
## 📚 VISSL Documentation

When installing VISSL using pip in a venv, the documentation states:
```
pip install apex -f https://dl.fbaipublicfiles.com/vissl/packaging/apexwheels/py38_cu101_pyt151/download.html
```
which installs the pypi package apex https://pypi.org/project/apex/. Instead the order of the arguments should be reversed:
```
pip install -f https://dl.fbaipublicfiles.com/vissl/packaging/apexwheels/py38_cu101_pyt151/download.html apex
```

System: Ubuntu 20.04.2 LTS, pip 20.0.2

**Comment by prigoyal** [comment]
thank you for pointing this out. Assigning to @bottler to take a look.
