### ISSUE TITLE
Pretrained RegNetY Models

### ISSUE THREAD

**Issue by imjwang** [facebookresearch/vissl#243]
## 🚀 Feature
Release RegNetY backbone family from [SEER](https://arxiv.org/pdf/2103.01988.pdf?fbclid=IwAR3wf563rVeO2HTu4PgKHV8mURnxl1KzrwYMrsp8F_UP8NY2-PwLZvzVs2g) pretrained on 1B Instagram pictures.

## Motivation & Examples
I could not find these models in the Model Zoo. Do you have plans to release them or did I miss them? The pretrained RegNets seem like great few shot learners. Maybe they will be great for downstream tasks with limited data.

**Comment by prigoyal** [comment]
Hi @imjwang , we currently don't have plans in near future to release the SEER model weights on 1B. Stay tuned to VISSL though for future updates on this particular item

**Comment by prigoyal** [comment]
closing this task as no further action is possible at this time
