### ISSUE TITLE
How can I use vissl as a package?

### ISSUE THREAD

**Issue by shivam-aggarwal** [facebookresearch/vissl#246]
I understand VISSL provides an easy way to train models via scripts and YAML configurations.
I am looking to integrate the features of VISSL in my project. I looking to use like:-
```
from vissl import swav

model = swav(config)

## do other stuff
```

Could you please help me with the same? Specifically when I am use it as a package on my local machine.
Thank You!

**Comment by prigoyal** [comment]
Hi @shivam-aggarwal , I'd recommend to go through the tutorials https://vissl.ai/tutorials/ and also VISSL modular components docs https://vissl.readthedocs.io/en/latest/index.html to use specific components of vissl.

Can you share further details on how you want the integration to look like: in the `model = swav(config)` above, is that the model built or a model trained? If you can share more specific details , we can help more.

**Comment by shivam-aggarwal** [comment]
Hi @prigoyal, thank you for responding ! 

The modular component docs helped especially the flowcharts. I am planning to use ```SelfSupervisionTrainer``` as a class for my training and testing purposes. I am planning to use it in an OOPs way because it provides more flexibility.

By ```model = swav(config)```,
 I meant creating an instance of the model. The usage will be followed by other methods like:-
```
model.load_checkpoints(path) / model.load_pretrained(path)
model.train() 
model.predict() 
```
Please let me know if you have any pointers for me.
Thanks!

**Comment by prigoyal** [comment]
@shivam-aggarwal , thank you so much for sharing the context above. For your use case scenario, definitely seems like using `SelfSupervisionTrainer` is the way to go. For building the model (or anything else), you can look at our task https://github.com/facebookresearch/vissl/blob/master/vissl/trainer/train_task.py#L404 and use the API calls like `vissl.models.build_model` etc . Also, look at `vissl/engines/train.py` https://github.com/facebookresearch/vissl/blob/master/vissl/engines/train.py that might be useful also to how we initialize the trainer. :)
