### ISSUE TITLE
Attribute error: NoneType has no 'keys'

### ISSUE THREAD

**Issue by Rebero** [facebookresearch/vissl#248]
I have been using Vissl since a couple of weeks and just ran into a problem when setting it up on a new machine (this didn't happen on the old machine). Every time I want to start a pre-training I get the following error:

 File "/opt/conda/envs/vissl/lib/python3.8/site-packages/vissl/utils/checkpoint.py", line 404, in init_model_from_weights
    state_dict_key_name in state_dict.keys()
AttributeError: 'NoneType' object has no attribute 'keys'

This also happens when just trying to replicating your tutorials such as the Training SimCLR on 1-gpu with VISSL.

Thank you.

-------------------  --------------------------------------------------------------------------
sys.platform         linux
Python               3.8.5 (default, Sep  4 2020, 07:30:14) [GCC 7.3.0]
numpy                1.19.2
Pillow               8.1.2
vissl                0.1.5 @/opt/conda/envs/vissl/lib/python3.8/site-packages/vissl
GPU available        True
GPU 0,1,2,3          Tesla V100-SXM2-16GB
CUDA_HOME            /usr/local/cuda
torchvision          0.8.2 @/opt/conda/envs/vissl/lib/python3.8/site-packages/torchvision
hydra                1.0.6 @/opt/conda/envs/vissl/lib/python3.8/site-packages/hydra
classy_vision        0.6.0.dev @/opt/conda/envs/vissl/lib/python3.8/site-packages/classy_vision
tensorboard          2.4.1
apex                 0.1 @/opt/conda/envs/vissl/lib/python3.8/site-packages/apex
PyTorch              1.7.1 @/opt/conda/envs/vissl/lib/python3.8/site-packages/torch
PyTorch debug build  False
-------------------  --------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

CPU info:
-------------------  -----------------------------------------
Architecture         x86_64
CPU op-mode(s)       32-bit, 64-bit
Byte Order           Little Endian
CPU(s)               32
On-line CPU(s) list  0-31
Thread(s) per core   2
Core(s) per socket   16
Socket(s)            1
NUMA node(s)         1
Vendor ID            GenuineIntel
CPU family           6
Model                79
Model name           Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
Stepping             1
CPU MHz              2698.234
CPU max MHz          3000.0000
CPU min MHz          1200.0000
BogoMIPS             4600.00
Hypervisor vendor    Xen
Virtualization type  full
L1d cache            32K
L1i cache            32K
L2 cache             256K
L3 cache             46080K
NUMA node0 CPU(s)    0-31
-------------------  -----------------------------------------

**Comment by prigoyal** [comment]
Hi @Rebero , there are some recent changes in fvcore dependency which seemed to have caused this problem. However, we have recently fixed it in master (just today in commit https://github.com/facebookresearch/vissl/commit/e44a49a45907c11726672617116c50cc0a0f306f )

Can you try to pull VISSL master and try again? If you can't pull master, the fix is essentially this line https://github.com/facebookresearch/vissl/blob/master/vissl/trainer/train_task.py#L464 :)

**Comment by Rebero** [comment]
Great, thanks so much for your prompt help.

**Comment by prigoyal** [comment]
Hi @Rebero , can you share more details on how to repro this? do you mean the error in the build or the error "Attribute error: NoneType has no 'keys'"?

**Comment by prigoyal** [comment]
update: 
I can't reproduce the installation error mentioned when installing from master in conda. For pip, our CircleCI runs pip and build status is green.

Sharing my conda, pip, python setup if it helps:
conda 4.9.2
pip 21.0.1
Python 3.7.10

Please provide the instructions to reproduce and open a new task as well for this :)

**Comment by Rebero** [comment]
Unfortunately the pip install --progress-bar off --upgrade iopath didn't resolve the issue. I made the edits in the conda installed vissl packaged directly just as you suggested, which works great. Thank you for your fantastic support.

**Comment by Rebero** [comment]
Happy to open a new task and share the steps to reproduce.
