### ISSUE TITLE
Which sinkhorn implementation

### ISSUE THREAD

**Issue by jrabary** [facebookresearch/vissl#250]
We are trying to figure out which sinkhorn implementation is used in the Swav model. 
It looks like you're using standard sinkhorn implementation with  an additional trick for numerical stabilisation but 
it is difficult to read the code and to match it with the original implementation. For example, in Swav the kernel is computed with exp(C/epsilon), in all other implementation it is exp(-C/epsilon). Why ?
Compared to the implantation of stabilized sinkhorn from https://pythonot.github.io your code looks very differents.
We did the test to compare the output of the implement of sinkhorn in swav and POT and we are not able to produces the same results. 
Can you bring some insight on this ?

**Comment by prigoyal** [comment]
Hi @jrabary , we implement the sinkhorn as in SwAV paper which notes the differences from the original sinkhorn (soft vs hard assignment for instance) https://arxiv.org/pdf/2006.09882.pdf. Please also see the appendix of the paper that outlines pseudo code algorithm for sinkhorn. 
Regarding why not `exp(-C/epsilon)` , what other implementations are you referring to?

**Comment by jrabary** [comment]
Thanks for you feedback. I'll give a look at the appendix.
For the exp(-C/eps) I'm referring to this one https://github.com/PythonOT/POT/blob/f6139428e70ce964de3bef703ef13aa701a83620/ot/bregman.py#L377

**Comment by prigoyal** [comment]
closing this task as no action is pending! please feel free to reopen for further questions or open a new task :)
