### ISSUE TITLE
Open cpus_per_task option for SLURM training 

### ISSUE THREAD

**Issue by OlivierDehaene** [facebookresearch/vissl#254]
## 🚀 Feature

It would be great to open the `cpus_per_task` option for SLURM training to the hydra config. Right now it is inferred from the number of processes per node i.e. the number of GPUs per node with a baseline value of 8 CPU per process. See: https://github.com/facebookresearch/vissl/blob/master/vissl/utils/distributed_launcher.py#L259

## Motivation & Examples

On the cluster I am using, we have 3 CPU per GPU in our octo-gpu nodes and 10 CPU per GPU in our quadri-gpu nodes. We need to be able to setup this value accordingly.

**Comment by OlivierDehaene** [comment]
Adding a `CPU_PER_PROC` with 8 as default value should be enough I think. What is your opinion on this?

**Comment by QuentinDuval** [comment]
First of all, I like the feature :) Go for it if you want to contribute it !

> Adding a `CPU_PER_PROC` with 8 as default value should be enough I think. What is your opinion on this?

The alternative would be to use the value inside `config.DATA.NUM_DATALOADER_WORKERS` since it parameterise the number of threads that will be popped to deal with the construction of batches.

I am not too sure which is best: it might not be that `NUM_DATALOADER_WORKERS` is the best amount of threads (maybe we just need one half), but on the other side, asking for 8 CPUs to use only 4 NUM_DATALOADER_WORKERS is probably a waste.

@OlivierDehaene, @prigoyal what do you think?

**Comment by prigoyal** [comment]
Indeed a nice feature request. I do think it makes sense for us to open the parity with the SLURM features in VISSL. Regarding #data workers and #cpus, this is something I think users should configure themselves and we should offer full flexibility.

@OlivierDehaene , @QuentinDuval , please feel free to grab the issue if you are interested in doing this. :)

**Comment by OlivierDehaene** [comment]
> The alternative would be to use the value inside `config.DATA.NUM_DATALOADER_WORKERS` since it parameterise the number of threads that will be popped to deal with the construction of batches.

I think it is better to have an independent parameter and raise an error or a warning if `NUM_DATALOADER_WORKERs > CPU_PER_PROC`. The reason I would prefer this implementation is because on our cluster, if we ask for more than 3 or 10 CPUs, SLURM will allocates more than the required number of nodes.

**Comment by OlivierDehaene** [comment]
Also, it would be great to add an option to pass `SLURM_ ADDITIONAL_PARAMETERS` to submitit. In my case I needed to add `{"account": ****}`.

Overall the changes would be:

defaults.yaml
```yaml
CONFIG:
...
    SLURM:
        CPU_PER_PROC: 8
        ADDITIONAL_PARAMETERS: {}
        ...
```

vissl/utils/distributed_launcher.py
```python
executor.update_parameters(
        name=cfg.SLURM.NAME,
        slurm_comment=cfg.SLURM.COMMENT,
        slurm_partition=cfg.SLURM.PARTITION,
        slurm_constraint=cfg.SLURM.CONSTRAINT,
        timeout_min=cfg.SLURM.TIME_HOURS * 60,
        nodes=cfg.DISTRIBUTED.NUM_NODES,
        cpus_per_task=cfg.CPU_PER_PROC * cfg.DISTRIBUTED.NUM_PROC_PER_NODE, #modified
        tasks_per_node=1,
        gpus_per_node=cfg.DISTRIBUTED.NUM_PROC_PER_NODE,
        mem_gb=cfg.SLURM.MEM_GB,
        slurm_additional_parameters=cfg.ADDITIONAL_PARAMETERS #added
    )
```

And then I can launch with:

```shell
./dev/launch_slurm.sh \
config=pretrain/barlow_twins/barlow_twins_4node_resnet.yaml \
config.SLURM.CPU_PER_PROC=10 \
config.SLURM.ADDITIONAL_PARAMETERS.ACCOUNT=****
```

**Comment by prigoyal** [comment]
looks great to me. @OlivierDehaene , do you want to open a PR with your proposed changes? :)

**Comment by prigoyal** [comment]
@OlivierDehaene , just an update: we are looking into this task ourselves and will keep posted on this issue of the progress.

**Comment by OlivierDehaene** [comment]
@prigoyal, Great! Sorry, I don't have time to work on VISSL at the moment.

**Comment by iseessel** [comment]
Hi @OlivierDehaene, I am new to the vissl team. I was able to get to your request here: https://github.com/facebookresearch/vissl/pull/282/files. Please look at the testing steps of the PR on how to use and let me know if you have any issues. 

Thanks for raising this issue and feel free to reopen if you have any more questions!
