### ISSUE TITLE
Changing model in Feature Extraction tutorial did not work for me

### ISSUE THREAD

**Issue by ToastyDom** [facebookresearch/vissl#255]
Hello everyone!
First of all, this is a really exciting toolbox - thank you for publishing it!

I am fairly new to working with config files so probably the mistake is on my side:

I tried changing the ResNet50-model from your feature extraction Colab tutorial to the SimClr one. To do that, I changed the download link to the weights but the rest remained the same. 

Later in the shell command I changed the name of the checkpoint so it looks like this:

`!python3 run_distributed_engines.py \
    hydra.verbose=true \
    config=extract_resnet_in1k_8gpu \
    +config/trunk_only=rn50_layers \
    config.DATA.TRAIN.DATA_SOURCES=[disk_folder] \
    config.DATA.TRAIN.LABEL_SOURCES=[disk_folder] \
    config.DATA.TRAIN.DATASET_NAMES=[dummy_data_folder] \
    config.DATA.TRAIN.BATCHSIZE_PER_REPLICA=2 \
    config.DATA.TEST.DATA_SOURCES=[disk_folder] \
    config.DATA.TEST.LABEL_SOURCES=[disk_folder] \
    config.DATA.TEST.DATASET_NAMES=[dummy_data_folder] \
    config.DATA.TEST.BATCHSIZE_PER_REPLICA=2 \
    config.DISTRIBUTED.NUM_NODES=1 \
    config.DISTRIBUTED.NUM_PROC_PER_NODE=1 \
    config.CHECKPOINT.DIR="./checkpoints" \
    config.MODEL.WEIGHTS_INIT.PARAMS_FILE="/content/model_final_checkpoint_phase999.torch" \
    config.MODEL.WEIGHTS_INIT.APPEND_PREFIX="trunk.base_model._feature_blocks." \
    config.MODEL.WEIGHTS_INIT.STATE_DICT_KEY_NAME=""`

This results in allocation errors on Colab and I don't know how to get around them.

`INFO 2021-03-25 11:12:35,260 util.py: 282: Loaded checkpoint from /content/model_final_checkpoint_phase999.torch
INFO 2021-03-25 11:12:35,260 util.py: 241: Broadcasting checkpoint loaded from /content/model_final_checkpoint_phase999.torch
tcmalloc: large alloc 1246027776 bytes == 0x55e7fac8c000 @  0x7fa802cfa615 0x55e647c6706c 0x55e647d46eba 0x55e647c6dacc 0x7fa7fe078a84 0x7fa7fe0807a4 0x7fa7fe056a30 0x7fa7ed436075 0x7fa7ed4325da 0x7fa7ed436a89 0x7fa7fe056f7e 0x7fa7fdc95c99 0x55e647c6ac38 0x55e647cde63d 0x55e647cd8e0d 0x55e647c6b77a 0x55e647cd9a45 0x55e647cd8b0e 0x55e647c6b77a 0x55e647cdde50 0x55e647cd8b0e 0x55e647c6b77a 0x55e647cd9a45 0x55e647cd8b0e 0x55e647c6b77a 0x55e647cda86a 0x55e647c6b69a 0x55e647cd9c9e 0x55e647c6b69a 0x55e647cd9c9e 0x55e647cd8b0e`

Is Colab too weak for the "rn50_w4_in1k_simclr_1000ep" - model? Or is there something else I have to consider? After all, the only thing I changed was the download file for the checkpoints...

I hope you can help me!

Thank you very much :)

**Comment by prigoyal** [comment]
Hi @ToastyDom , thank you for reaching out. It seems like you are interested in extracting features for a RN50-w4 model. In that case you should chose the appropriate trunk instead of `rn50_layers` . For instance, you can modify the `rn50_layers` file to match the RN50-w4 model as we've done here https://github.com/facebookresearch/vissl/blob/master/configs/config/benchmark/linear_image_classification/imagenet1k/models/resnet50_w4.yaml

Can you also confirm if running the RN50 model works for you?

**Comment by ToastyDom** [comment]
Hello @prigoyal , thank you for your quick response! Oh right, it makes sense to use the w4 config file! However, the error remains. I tried it with that exact file you provided and with the original one but with an added `WIDTH_MULTIPLIER: 4` (see below). I even tried adding the multiplier to the "extract_resnet_in1k_8gpu.yaml" file, but that did not do the trick either. It must be something with the configs though, I tried a SimClr Model that uses a normal ResNet, which worked fine.
Is there anything else I could try?
So far I did:

1. Changing the checkpoints
2. Using "resnet50_w4.yaml" instead of "rn50_layers.yaml"
3. Adding WIDTH_MULTIPLIER: 4 to "extract_resnet_in1k_8gpu.yaml"


After using the "resnet50_w4.yaml" file, this is how I added the width multiplier to the "rn50_layers.yaml" setup:
```

> # @package _global_
> config:
>   MODEL:
>     FEATURE_EVAL_SETTINGS:
>       EVAL_MODE_ON: True
>       FREEZE_TRUNK_ONLY: True
>       EXTRACT_TRUNK_FEATURES_ONLY: True
>       SHOULD_FLATTEN_FEATS: False
>       LINEAR_EVAL_FEAT_POOL_OPS_MAP: [
>         ["conv1", ["AvgPool2d", [[10, 10], 10, 4]]],
>         ["res2", ["AvgPool2d", [[16, 16], 8, 0]]],
>         ["res3", ["AvgPool2d", [[13, 13], 5, 0]]],
>         ["res4", ["AvgPool2d", [[8, 8], 3, 0]]],
>         ["res5", ["AvgPool2d", [[6, 6], 1, 0]]],
>         ["res5avg", ["Identity", []]],
>       ]
>     TRUNK:
>       NAME: resnet
>       TRUNK_PARAMS:
>         RESNETS:
>           DEPTH: 50
>           WIDTH_MULTIPLIER: 4

```
         

I hope you have an idea of what else I could try!
Best regards :)

**Comment by prigoyal** [comment]
thank you @ToastyDom  :) I am suspecting that this is related to the colab infra . Would it be possible to install VISSL from source https://github.com/facebookresearch/vissl/blob/stable/INSTALL.md#install-from-source-in-pip-environment and then give it a try on your machine? this will allow us to isolate whether it's the issue of VISSL or colab :)

**Comment by ToastyDom** [comment]
My computer is sadly not strong enough - I will upgrade soon though ;) For now, the normal ResNet backbones do well enough for my purposes though! I'm sorry, that I cannot test that out, but thank you very much for your responses, they were very helpful!
