### ISSUE TITLE
Hardware Used and Time Taken to Produce Models in Model Zoo

### ISSUE THREAD

**Issue by mmaaz60** [facebookresearch/vissl#270]
## 📚 VISSL Documentation

Hi, 

I was wondering which hardware did you use and how much time did it take to train the models listed in Moel Zoo. These stats would be beneficial to do a comprehensive comparison of the time complexity of the methods. Though these details can be found in the corresponding papers, but different papers are using different hardware, and documenting these details on similar hardware would be beneficial.

Grateful,
Muhammad Maaz

**Comment by prigoyal** [comment]
Hi @mmaaz60 , thank you for reaching out. We use Nvidia gpus : V100 16GB or V100 32GB (depending on if the memory was a constraint). For the model zoo, we list the specifications in several json files provided at https://github.com/facebookresearch/vissl/tree/master/configs/config/model_zoo. For example for SwAV and deepclusterV2 models in the model zoo, the specifications can be found like: https://github.com/facebookresearch/vissl/blob/master/configs/config/model_zoo/benchmark_in1k_linear_deepclusterv2_swav.json#L16-L20

**Comment by mmaaz60** [comment]
> Hi @mmaaz60 , thank you for reaching out. We use Nvidia gpus : V100 16GB or V100 32GB (depending on if the memory was a constraint). For the model zoo, we list the specifications in several json files provided at https://github.com/facebookresearch/vissl/tree/master/configs/config/model_zoo. For example for SwAV and deepclusterV2 models in the model zoo, the specifications can be found like: https://github.com/facebookresearch/vissl/blob/master/configs/config/model_zoo/benchmark_in1k_linear_deepclusterv2_swav.json#L16-L20

Thank you @prigoyal, what about training time of the models under these configurations? Do you have any such records?

**Comment by prigoyal** [comment]
> > Hi @mmaaz60 , thank you for reaching out. We use Nvidia gpus : V100 16GB or V100 32GB (depending on if the memory was a constraint). For the model zoo, we list the specifications in several json files provided at https://github.com/facebookresearch/vissl/tree/master/configs/config/model_zoo. For example for SwAV and deepclusterV2 models in the model zoo, the specifications can be found like: https://github.com/facebookresearch/vissl/blob/master/configs/config/model_zoo/benchmark_in1k_linear_deepclusterv2_swav.json#L16-L20
> 
> Thank you @prigoyal, what about training time of the models under these configurations? Do you have any such records?

Typically for all the models for the specified #gpus used, it's few hours (ranging between 3 hrs - 24 hours)

**Comment by prigoyal** [comment]
closing this issue as no further actionable steps are remaining. Please feel free to reopen the issue in case of any follow-up questions or feel free to open a new one :)
