### ISSUE TITLE
[feature] Dataset Catalog Environment Variable for Local Development

### ISSUE THREAD

**Issue by iseessel** [facebookresearch/vissl#280]
## 🚀 Feature

Add ability to use a different dataset_catalog.json through the use of an environment variable and/or through the hydra config.

## Motivation & Examples

The immediate use case is for local development. That is we can have a `dataset_catalog_local.json`, that we can have gitignored for ease of local development. This will be helpful in terms of managing git when we need to change the dataset_catalog. 

Other use cases could be for having different dataset catalogs for different environments, etc., 

The idea would be to set an environment variable called VISSL_DATASET_CATALOG_PATH. Then in get_json_data_catalog_file, we look for the environment variable and fallback to the the default the dataset_catalog.json.

We could potentially put the catalog in the YAML config. We might be able to do both with the following hierarchy YAML CONFIG => ENVIRONMENT VARIABLE => Default.

**Comment by prigoyal** [comment]
PR landed, closing the issue :) thank you @iseessel  :)
