### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by lewfish** [facebookresearch/vissl#281]
This Github repo (and several other Facebook SSL repos) use a Creative Commons Attribution-NonCommercial 4.0 International Public License. I understand that I cannot sell this or modified copies of this code, and would need to license adapted versions of this code under the same license. But, does this license mean that I am not allowed to *run* this code for commercial purposes? As an example, would I be able to use VISSL to pretrain a model on my own data and then use those weights in a commercial project? Taking it a step further, would I be able to take the pretrained weights distributed with VISSL, fine-tune them on another dataset, and then use the resulting weights for commercial purposes?

**Comment by prigoyal** [comment]
thank you for reaching out about this. I have asked for clarifications on this and will share an update. I am also looking into changing license to Apache to make it more open. I'll keep this issue updated.

**Comment by howard-mahe** [comment]
Hello Priya, thanks a lot for work! Any update on the legal question?

**Comment by prigoyal** [comment]
Hi @howard-mahe, I will be updating the VISSL license to MIT today / tomorrow :) I've just received the approval.

**Comment by OlivierDehaene** [comment]
@prigoyal this is huge! Thanks a lot! :)

**Comment by prigoyal** [comment]
VISSL is MIT license now, closing this issue :)
