### ISSUE TITLE
U-Net Integration

### ISSUE THREAD

**Issue by yuriyvl** [facebookresearch/vissl#289]
## ❓ How to do something using VISSL

Hello.  Are there any plans to add support for [U-Net](https://arxiv.org/abs/1505.04597) in the near future?  Unfortunately it is not on the list of the provided [trunks](https://github.com/facebookresearch/vissl/tree/master/vissl/models/trunks).  

If this is not planned, how would you suggest going about it?  Our research project requires usage of U-Net for analysis and comparison.  We would love to use VISSL to help with the implementation, but this one link is missing.

Thank you in advance.

**Comment by prigoyal** [comment]
Hi @yuriyvl , thank you so much for reaching out about this.

U-Net is currently not planned in VISSL but we would certainly accept any contributions and provide the support needed for it.

To go about this, I'd recommend reading the doc https://vissl.readthedocs.io/en/v0.1.5/extend_modules/models.html#adding-new-trunks which outlines the steps to add a new trunk. LMK if you have any questions. :)

**Comment by prigoyal** [comment]
@yuriyvl , yes absolutely :) feel free to use this thread.

**Comment by sbelenki** [comment]
Hi @prigoyal , thank you very much for this great framework!
We were able to successfully integrate it with UNet (the original one used in the [fastMRI project](https://github.com/facebookresearch/fastMRI)) and with NestedUNet (AKA UNet++, based on the [4uiiurz1 implementation](https://github.com/4uiiurz1/pytorch-nested-unet)) - [yuriyvl](https://github.com/yuriyvl), [sbelenki](https://github.com/sbelenki), [dschmidlin](https://github.com/dschmidlin) and [comshak](https://github.com/comshak) from GaTech were working on this project.
Unfortunately we won't be able to make a formal PR as our project is tightly coupled with the [fastMRI project](https://github.com/facebookresearch/fastMRI) and their dependency on the h5py package that we had to add to our copy of the [VISSL ssl_transforms](https://github.com/sbelenki/vissl/tree/master/vissl/data/ssl_transforms) (we've added the following new transforms: SpatialToFrequency, ApplyFrequencyMask, FrequencyToSpatial, ToOneChannelTensor)
Just to contribute several examples to the VISSL project I've pushed our cloned/modified VISSL repo containing UNet/UNet++ integration here https://github.com/sbelenki/vissl 
The UNet integration configurations that worked for us are in the following YAMLs:
[vissl/configs/config/pretrain/pirl/pirl_jigsaw_unet.yaml](https://github.com/sbelenki/vissl/blob/master/configs/config/pretrain/pirl/pirl_jigsaw_unet.yaml)
[vissl/configs/config/pretrain/rotnet/rotnet_8gpu_unet.yaml](https://github.com/sbelenki/vissl/blob/master/configs/config/pretrain/rotnet/rotnet_8gpu_unet.yaml)
[vissl/configs/config/pretrain/simclr/simclr_4node_unet_traintest.yaml](https://github.com/sbelenki/vissl/blob/master/configs/config/pretrain/simclr/simclr_4node_unet_traintest.yaml)
And the UNet++ integration is in the [vissl/configs/config/pretrain/swav/swav_8node_nestedunet_fastmri.yaml](https://github.com/sbelenki/vissl/blob/master/configs/config/pretrain/swav/swav_8node_nestedunet_fastmri.yaml)

**Comment by prigoyal** [comment]
thank you @sbelenki for the update :) I am really glad to know that the Unet integration was successful and really appreciate all the pointers. 

We are looking into adding a few medical imaging related benchmarks as well to VISSL and exploring it with Matthew Muckley (one of the contributors of the FastMRI project). 

Out of curiosity: it sounds like the blockers in contributing to the VISSL is primarily the h5py dependency? Is there something that VISSL team can do to help remove the blockers and enable your contribution to VISSL ? :) I love the work you've done and would like to help make it available to VISSL community (if this is of interest to you) :)

**Comment by sbelenki** [comment]
Hi @prigoyal, other than h5py in the [fastmri_dataset.py](https://github.com/sbelenki/vissl/blob/master/vissl/data/fastmri_dataset.py), we had to copy several portions of the fastMRI code into the new [FrequencyToSpatial](https://github.com/sbelenki/vissl/blob/master/vissl/data/ssl_transforms/freq_to_spatial.py) and [ApplyFrequencyMask](https://github.com/sbelenki/vissl/blob/master/vissl/data/ssl_transforms/freq_apply_mask.py) SSL transforms (you can see they're credited to the fastMRI repo in the comments). It’s a bit ugly workaround, but not sure how else we could avoid this code duplication as VISSL wasn’t designed to work with the frequency domain and we didn’t want to make it dependent on the [fastmri core](https://github.com/facebookresearch/fastMRI/tree/master/fastmri).
Please convey our big thank you to Matthew Muckley and Mark Tygert, they were very instrumental in helping everyone on the AI Learning forum last semester!

**Comment by prigoyal** [comment]
closing this thread :) I am glad this worked out and feel free to reach out for anything we can support on in future :)
