### ISSUE TITLE
ConViT: documentation and model

### ISSUE THREAD

**Issue by prigoyal** [facebookresearch/vissl#297]
We landed the Convit code and want to accomplish the next few steps:

- [x] Documentation
    - [x] documentation in `docs/source/ssl_approaches` @growlix 
    - [x] optional: add doc to projects/ folder @growlix 
- [ ] Model zoo
    - [ ] a script to train and evaluate @growlix 
    - [ ] train a model and evaluate @vedanuj 
    - [ ] Add the model to AWS and to the model zoo (@prigoyal can help coordinate this)

**Comment by prigoyal** [comment]
going to close this. documentation is in and we will aim to rather push the moco-v3 implementation.

**Comment by iseessel** [comment]
ConViT released in latest release: https://github.com/facebookresearch/vissl/releases/tag/v0.1.6.

Documentation is here: https://vissl.readthedocs.io/en/v0.1.6/ssl_approaches/vision_transformers.html?highlight=convit#convit
