### ISSUE TITLE
Example Colab File on top-level README is no longer working.

### ISSUE THREAD

**Issue by jotterbach** [facebookresearch/vissl#300]
## 📚 VISSL Documentation

A clear and concise description of what content in the [Docs](https://github.com/facebookresearch/vissl/tree/master/docs) is an issue.

Trying to execute the VISSL [example notebook ](https://colab.research.google.com/drive/1DkqGi9L47eWjA5j77EVEmbrktWBGoynN?usp=sharing#scrollTo=ayNfZrhdPnOu) `Using a pretrained model for inference` from the main README.md and running into execution errors deep in the VISSL code (see screenshot). Seems the schema changed, since I cannot access the attribute either when dotting into the config object.

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/5595043/115766976-e2cf4600-a3a8-11eb-829e-aa12509f2825.png">

**Comment by prigoyal** [comment]
Hi @jotterbach , did you install VISSL from packages or installed from master?

**Comment by jotterbach** [comment]
Hi @prigoyal, I simply executed the collab notebook which installs the pip package. I was able to run it later when I installed the master by hand, then the notebook ran.

**Comment by prigoyal** [comment]
sounds great. thank you @jotterbach for reaching out about this. We will look into making it further clear in the tutorials about the compatibility of the configs file :) 

closing this issue as it seems resolved, feel free to reopen for any follow-up questions or open a new issue :)

**Comment by 5agado** [comment]
Thank again for the great work!
I just wanted to highlight that the example notebook linked in the README still throws the same error reported above, and it is not clear what is the way around it. Manually installing the master by hand throws other errors.

As these are the introductory notebooks highlighted in the repo README it would be nice to have them to work as they are, or at least to add some disclamair at the top specifying workarounds or general warnings.
