### ISSUE TITLE
Performance discrepancy in SimCLR?

### ISSUE THREAD

**Issue by spurra** [facebookresearch/vissl#301]
First of, huge compliments on this great library! It accelerates developing these kinds of self-supervised methods a lot.

I've got a question regarding the reported SimCLR performance: https://github.com/facebookresearch/vissl/blob/master/MODEL_ZOO.md#simclr
They seem to differ from what what the official SimCLR implementation report: https://github.com/google-research/simclr#pre-trained-models-for-simclrv1

What accounts for this difference?

**Comment by prigoyal** [comment]
Hi @spurra , thank you so much for reaching out about this and also really happy to hear about the library being useful :)

Regarding the SimCLR performance:
1. For ResNet50, we report `RN50 - 800 epochs | ImageNet-1K | 69.68` which in Google's repo `ResNet50 (1x) | 69.1`
2. For ResNet50 (2x), we report `RN50-w2 - 1000 epochs | ImageNet-1K | 73.84` which in Google's repo is `ResNet50 (2x) | 74.2`. The difference of 0.36 is expected experimental standard deviation (we report model for one training run)
3. For ResNet50 (4x), we report `RN50-w4 - 1000 epochs | ImageNet-1K | 71.61` which is lower than Google's number of 76.6. RN50-4x is a model that we blindly trained  using the same hyperparams as RN50-2x or RN50. With that said, this is probably something we should investigate but I believe it's just a matter of verifying the training parameters for this specific model. Often for large models, the training settings could be different for better stability/performance.

**Comment by spurra** [comment]
Thank you very much for the rapid response! That clarifies any concerns I had :)
