### ISSUE TITLE
Values for mean and std in Normalize Data Transform

### ISSUE THREAD

**Issue by pcanas** [facebookresearch/vissl#302]
In all the example config files described in the [Tutorials](https://vissl.ai/tutorials/), there is a _Normalize_ Data Transform, with the following mean and std:

```
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]
```

I was wondering what is the reason for these values. Are they specific for the Imagenet_1k dataset? Should I calculate my own values if my plan is to use a custom dataset?

Thank you for your help!

**Comment by prigoyal** [comment]
Hi @pcanas , these are legacy values that are used for most datasets not just imagenet. I don't think you necessarily need to compute these values for your dataset. Within VISSL itself, we use the values for many datasets example https://github.com/facebookresearch/vissl/blob/master/configs/config/benchmark/linear_image_classification/dsprites/eval_resnet_8gpu_transfer_dsprites_loc_linear.yaml#L39-L41

That said, I think for research curiosity, I always encourage to experiment to find the new values for your dataset and see what you observe :)
