### ISSUE TITLE
fvcore version of PathManager will be deprecated soon

### ISSUE THREAD

**Issue by spurra** [facebookresearch/vissl#305]
According to https://github.com/facebookresearch/fvcore/issues/47 I've replaced all import statements of fvcore that import PathManager with iopath

However during the training loop the following message still appears:

** fvcore version of PathManager will be deprecated soon. **                                                                                 
** Please migrate to the version in iopath repo. **                                                                                          
https://github.com/facebookresearch/iopath      

Where is this message coming from? These repeated messages clutter the terminal output.

**Comment by prigoyal** [comment]
Hi @spurra , thank you for reaching out. This is coming from the fvcore repo itself which is asking to migrate to the iopath. We plan to do this migration over next few weeks and before the next VISSL release .

**Comment by spurra** [comment]
I see, thanks for the quick response!

**Comment by yxchng** [comment]
@prigoyal Seems like the migration has not been done? I am also getting lots of these messages
