### ISSUE TITLE
Precision and Recall Meters 

### ISSUE THREAD

**Issue by zlapp** [facebookresearch/vissl#313]
Noticed there isn't an implementation of precision and recall.
Below is an initial implementation happy to PR.
https://github.com/zlapp/vissl/tree/master/vissl/meters

**Comment by prigoyal** [comment]
Hi @zlapp , thank you so much. Please go ahead and send a PR for this if you'd like :) thank you!

**Comment by zlapp** [comment]
Thank you @prigoyal happy to contribute! Keep up the great work! https://github.com/facebookresearch/vissl/pull/312

**Comment by zlapp** [comment]
@prigoyal I'm new to hydra, was wondering how would it be possible to run a benchmark (i.e. linear eval) with multiple meters and if it is currently supported?
