### ISSUE TITLE
Custom Dataset not registered

### ISSUE THREAD

**Issue by khizirsiddiqui** [facebookresearch/vissl#329]
I am trying to use memotion dataset following the [tutorials](https://colab.research.google.com/drive/1Rt3Plt3ph84i1A-eolLFafybwjrBFxYe?usp=sharing) and [documentation](https://vissl.readthedocs.io/en/latest/extend_modules/custom_datasets.html) available. I register it in the `VisslDatasetCatalog` and confirm it by printing the entries.

```python
from vissl.data.dataset_catalog import VisslDatasetCatalog
VisslDatasetCatalog.register_data(name="memotion", data_dict={"train": ['/content/memotion_dataset_7k/train1', '/content/memotion_dataset_7k/train1'] , "val": ['/content/memotion_dataset_7k/test1', '/content/memotion_dataset_7k/test1']})
for k in VisslDatasetCatalog.list():
    print(k, VisslDatasetCatalog.get(k))
```
This shows an output: 
```
memotion {'train': ['/content/memotion_dataset_7k/train1', '/content/memotion_dataset_7k/train1'], 'val': ['/content/memotion_dataset_7k/test1', '/content/memotion_dataset_7k/test1']}
```

I run the training process from the tutorial as 
```bash
python3 run_distributed_engines.py \
    hydra.verbose=true \
    config=quick_1gpu_resnet50_simclr \
    config.DATA.TRAIN.DATA_SOURCES=[disk_folder] \
    config.DATA.TRAIN.DATASET_NAMES=[memotion] \
    config.DATA.TRAIN.DATA_PATHS=["/content/memotion_dataset_7k/train1"] \
    config.DATA.TEST.DATA_SOURCES=[disk_folder] \
    config.DATA.TEST.DATASET_NAMES=[memotion] \
    config.DATA.TEST.DATA_PATHS=["/content/memotion_dataset_7k/test1"] \
    config.OPTIMIZER.num_epochs=100 \
    config.CHECKPOINT.DIR="./checkpoints" 
```

I receive an error:
```bash
File "/usr/local/lib/python3.7/dist-packages/vissl/data/dataset_catalog.py", line 84, in get
    name, ", ".join(VisslDatasetCatalog.__REGISTERED_DATASETS.keys())
KeyError: "Dataset 'memotion' is not registered! Available datasets are: "
```

Strangely, if I add `config.TENSORBOARD_SETUP.USE_TENSORBOARD=true`, the error is not thrown and instead the training stops after outputting this in logs:
```
INFO 2021-05-28 11:02:38,242 tensorboard.py:  46: Tensorboard dir: ./checkpoints/tb_logs
```

My directory structure is as:
```
/content/memotion_dataset_7k/<train1/test1>
      |
      |--class0
      |        |---abc.jpg
      |        |---abcdef.jpg
      |        ......
      |--class1
      |        |---abcxyz.jpg
      |        |---abcqwe.jpg
      .        .....
      ......
```
I am using Google Colab to run the experiements.

**Comment by prigoyal** [comment]
thank you for reporting this @khizirsiddiqui . :) A few follow-up questions to help with this:

1) are you directly installing the VISSL package (as in the tutorial)? or did you install VISSL master from source?
2) when you add the tensorboard command, do you mean the training happens as expected?

**Comment by khizirsiddiqui** [comment]
Hello!!
1) Directly installing the VISSL package as in tutorial.
2) No, the execution of script stops - without any updates in logs or any errors, reported `INFO` mesage is the last logged statement.

**Comment by iseessel** [comment]
Hi @khizirsiddiqui, can you try creating the `dataset_catalog.json` and adding your entry? You can see it done in this tutorial: https://vissl.ai/tutorials/Understanding_VISSL_Training_and_YAML_Config#Using-the-custom-data-in-VISSL and here's a reference to the documentation. https://vissl.readthedocs.io/en/latest/vissl_modules/data.html#using-dataset-catalog-json. LMK if that works!

**Comment by khizirsiddiqui** [comment]
Hello @iseessel , yes it works this way.
