### ISSUE TITLE
Impossible to use custom multicrop transform with SwAV etc.

### ISSUE THREAD

**Issue by norabelrose** [facebookresearch/vissl#339]
I am trying to train a SwAV model on images that have a lot of completely featureless, uniformly black background, so I wrote a custom multicrop transform that only samples crops from the non-background regions (which are irregularly shaped). But I am running into a problem because `infer_losses_config()` in `vissl/utils/hydra_config.py` only automatically sets the `num_crops` parameter of `SwaAVLoss` when an `ImgPilToMultiCrop` transform is used, and it does so in a way that makes it **impossible to manually set the `num_crops` parameter in the config file**. In particular, `infer_losses_config()` unconditionally assigns the `num_crops` parameter to the expression
```
total_num_crops = next(
        (
            transform
            for transform in train_transforms
            if transform["name"] == "ImgPilToMultiCrop"
        ),
        None,
)
```
which is of course `None` if there are no `ImgPilToMultiCrop` transforms. This clobbers over any value that `num_crops` may already have due to the user setting it manually. This then causes the following error when you try to train the model:

<img width="640" alt="Screen Shot 2021-06-11 at 11 48 35 AM" src="https://user-images.githubusercontent.com/39116809/121738804-8dadd780-caaf-11eb-8c20-37d2cafd7f12.png">

I found that the error is fixed if I change line 367 of `hydra_config.py` to:
```
if total_num_crops:
    cfg.LOSS.swav_loss.num_crops = total_num_crops
```
I consider this a bug because you are supposed to be able to implement your own transforms, but this behavior makes it essentially impossible, at least through the Hydra/YAML interface, without directly modifying the source code. So my official recommendation would be that the above change (preventing `infer_losses_config()` from clobbering over user-defined values) should be merged into master, and should probably also be implemented for all the relevant losses, not just SwAV.

PS: I also had to include the following code in my custom transform file to get the code to work, which is not super great, but I'm not sure it qualifies as a bug:
```
from vissl.data.ssl_transforms.ssl_transforms_wrapper import _TRANSFORMS_WITH_COPIES
# Let VISSL know that our custom transform creates multiple copies of each input
_TRANSFORMS_WITH_COPIES += ["BackgroundAwareMultiCrop"]
```

## Instructions To Reproduce the 🐛 Bug:

1. Manually set the `num_crops` parameter of `SwAVLoss` in a config file and watch nothing happen
2. If you want my specific error, just make a copy of `ImgPilToMultiCrop`, register it as a custom transform under a different name, and then try to use that transform in a SwAV config file with the `num_crops` parameter set manually.

**Comment by prigoyal** [comment]
assigning to @iseessel , will you be able to look ? :)

**Comment by iseessel** [comment]
Hi @norabelrose thanks for reaching out! 

1. Indeed this is a bug, introduced by https://github.com/facebookresearch/vissl/pull/317/files. I should have a PR to fix soon. Just a bit of context, the reason why we overwrite config options is to prevent difficult-to-debug errors or silent failures mismatches in user provided configs. That being said, this is obviously a bug.

2. As for the below -- I agree this is not the best user experience. We can discuss how to improve this -- please let us know if you had any alternatives in mind.  

```
from vissl.data.ssl_transforms.ssl_transforms_wrapper import _TRANSFORMS_WITH_COPIES
# Let VISSL know that our custom transform creates multiple copies of each input
_TRANSFORMS_WITH_COPIES += ["BackgroundAwareMultiCrop"]
```

**Comment by iseessel** [comment]
Hi @norabelrose, we have a PR up: https://github.com/facebookresearch/vissl/pull/345 Let me know how this looks to you :D.

**Comment by iseessel** [comment]
Closing as this if fixed by: https://github.com/facebookresearch/vissl/pull/345. Please let us know if you have any other issues :).
