### ISSUE TITLE
How to get the representation  vector of certain image

### ISSUE THREAD

**Issue by 312shan** [facebookresearch/vissl#340]
Hi there,
I run this [Extracting Features from a pretrained model](https://colab.research.google.com/drive/1EXZyW65lXBryWE2ZmC0bar2996KEiBZb?usp=sharing) aims to extraction images' feature vector , but how can i get the representation  vector of certain image, or get the image_file_name2vector  mapping dict ? 

I has been print to explore  *ids.npy , *feature.npy ,but there only feature , i can't figure out image_file_name2vector relation.

**Comment by prigoyal** [comment]
Hi @312shan , thank you for reaching out. I am not sure I understand the question. The feature vectors in `*feature.npy` correspond to the image `*ids.npy` where the data is built using Torchvision `ImageFolder` https://github.com/facebookresearch/vissl/blob/master/vissl/data/disk_dataset.py#L85-L86 . You can inspect the torchvision https://github.com/pytorch/vision/blob/master/torchvision/datasets/folder.py#L272 to get information about the image file names for each image idx.

**Comment by iseessel** [comment]
@312shan Let us know if you want me to re-open this!
