### ISSUE TITLE
JSON file format changes due to appending

### ISSUE THREAD

**Issue by pranavsinghps1** [facebookresearch/vissl#342]
## JSON file format changes due to appending
 Re-running the 
```
from vissl.utils.io import save_file
save_file(json_data, "/content/configs/config/dataset_catalog.json")
``` 

appends to the existing JSON file instead of re-writing it, this leads to a JSONDecoderError, which means the JSON file is not of the appropriate format.

## Expected behavior:

Changing the
 ```save_file(json_data, "/content/configs/config/dataset_catalog.json")``` to something that re-writes it instead of appending would help solve the problem.

Right now to fix it the file (dataset_catalog.json) needs to be deleted before re-running the above code snippet.

## Environment:

I used google Colab to run the jupyter notebooks: 
https://github.com/facebookresearch/vissl/blob/master/tutorials/Understanding_VISSL_Training_and_YAML_Config.ipynb
 and also in https://github.com/facebookresearch/vissl/blob/master/tutorials/Benchmark_Full_Finetuning_on_ImageNet_1K.ipynb

**Comment by prigoyal** [comment]
Hi @pranavsinghps1 , thank you for reporting this. Indeed, I think we should support optional user input on whether to re-write and append i.e. something like `save_file(json_data, "my_file.json", rewrite=False)`  so user can configure and control this.

**Comment by iseessel** [comment]
Fixed by: https://github.com/facebookresearch/vissl/pull/346
