### ISSUE TITLE
Windows Installation

### ISSUE THREAD

**Issue by marcomameli1992** [facebookresearch/vissl#351]
## ❓ How to do something using VISSL

I'm trying to install VISSL on my windows computer that has an NVIDIA GPU. I'm using the command: 
' conda install -c vissl -c iopath -c conda-forge -c pytorch -c defaults apex vissl '

but I receive a not found package for apex and VISSL

**Comment by prigoyal** [comment]
Hi @marcomameli1992 , thank you for reaching out. We don't provide conda packages for Windows. However, you can install VISSL from source following our instructions. For apex, you should check the apex github repo if it works for windows . If it doesn't, then I think you can just skip apex. For most of the apex functionality, pytorch provides everything now and e can help you with that.

**Comment by iseessel** [comment]
Closing this because we haven't heard back in awhile. @marcomameli1992 let us know if you want us to re-open/need any additional guidance!
