### ISSUE TITLE
save_file

### ISSUE THREAD

**Issue by youyeg** [facebookresearch/vissl#358]
Ran the codes according to https://github.com/facebookresearch/vissl/blob/master/GETTING_STARTED.md, and I got the following error:

1. what changes you made (`git diff`) or what code you wrote
```
```
2. what exact command you run:
save_file(json_data, "/tmp/configs/config/dataset_catalog.json", append_to_json=False)
3. what you observed (including __full logs__):
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: save_file() got an unexpected keyword argument 'append_to_json'
```

## Expected behavior:
run as explained in https://github.com/facebookresearch/vissl/blob/master/GETTING_STARTED.md

**Comment by pranavsinghps1** [comment]
Hey, @youyeg  thank you for bringing this to our attention! 
Could you please tell us the steps that you used for installing vissl ?

**Comment by youyeg** [comment]
Hi @pranavsinghps1 
I did exactly as it said in here. https://github.com/facebookresearch/vissl/blob/master/GETTING_STARTED.md
For the installation also, I followed conda installation.
I didn't get any error message by that line.
I also removed `", append_to_json=False`, and I got this:
`>>> save_file(json_data, "/tmp/configs/config/dataset_catalog.json")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yousef/anaconda3/envs/vissl/lib/python3.8/site-packages/vissl/utils/io.py", line 65, in save_file
    with PathManager.open(filename, "a") as fopen:
  File "/home/yousef/anaconda3/envs/vissl/lib/python3.8/site-packages/iopath/common/file_io.py", line 1012, in open
    bret = handler._open(path, mode, buffering=buffering, **kwargs)  # type: ignore
  File "/home/yousef/anaconda3/envs/vissl/lib/python3.8/site-packages/iopath/common/file_io.py", line 604, in _open
    return open(  # type: ignore
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/configs/config/dataset_catalog.json'`

**Comment by pranavsinghps1** [comment]
The pip installation package is a bit back-dated, some of the changes introduced including the addition of append_to_json in the save_file function have been done recently, and hence haven't been addressed in the pip package.
A solution to this is to install from the source.
You can follow the vissl installation process as shown in : https://colab.research.google.com/drive/1KqrvOs5fsu5tbxDF_wNEPJX-OU_RoeG9?usp=sharing

Hope this helps!

**Comment by youyeg** [comment]
Thanks, it worked. I checked the colab yesterday, and it also didn't work. I think you fixed it also.
BTW, I tried colab, pip, conda, and all of them had some errors. This is the only one that worked.

**Comment by pranavsinghps1** [comment]
> Thanks, it worked. I checked the colab yesterday, and it also didn't work. I think you fixed it also.
> BTW, I tried colab, pip, conda, and all of them had some errors. This is the only one that worked.

CC: @prigoyal Fixed

**Comment by prigoyal** [comment]
thank you @pranavsinghps1 , closing this issue ! :)
