### ISSUE TITLE
typo in weight conversion 

### ISSUE THREAD

**Issue by sinberlin2** [facebookresearch/vissl#365]
Converting to ClassyVision
All the ResNe(X)t models in VISSL can be converted to Detectron2 weights using following command:

should be: 
All the ResNe(X)t models in VISSL can be converted to **ClassyVision** weights using following command:

**Comment by iseessel** [comment]
@sinberlin2 Thanks for pointing this out. Would you be open to submitting a quick PR to fix :)?
