### ISSUE TITLE
Error Importing 'TrainingMode' from 'torch.onnx'

### ISSUE THREAD

**Issue by rcterrile** [facebookresearch/vissl#373]
## Instructions To Reproduce the 🐛 Bug:

I am new to VISSL and trying to lean using the tutorial notebooks.  When running "Understanding VISSL Training and YAML Config.ipynb" (the second tutorial notebook) in Google Colab the following line causes an error.

1. Exact command run:
```
from vissl.data.dataset_catalog import VisslDatasetCatalog
```
2. This is the observed output (including __full logs__):
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-8-b5479c1fc208> in <module>()
----> 1 from vissl.data.dataset_catalog import VisslDatasetCatalog
      2 
      3 # list all the datasets that exist in catalog
      4 print(VisslDatasetCatalog.list())
      5 

11 frames
/usr/local/lib/python3.7/dist-packages/torch/onnx/utils.py in <module>()
     17 from torch._six import string_classes
     18 from torch.jit import _unique_state_dict
---> 19 from torch.onnx import ONNX_ARCHIVE_MODEL_PROTO_NAME, ExportTypes, OperatorExportTypes, TrainingMode
     20 from torch._C import ListType, OptionalType, _propagate_and_assign_input_shapes, _check_onnx_proto
     21 from typing import Union, Tuple, List

ImportError: cannot import name 'TrainingMode' from 'torch.onnx' (/usr/local/lib/python3.7/dist-packages/torch/onnx/__init__.py)
```
I have not changed any code in any way, I am just running the code boxes provided and getting this error.  This is all on Google Colab.

## Environment:

3. The environment information is as follows:
```
-------------------  ---------------------------------------------------------------
sys.platform         linux
Python               3.7.11 (default, Jul  3 2021, 18:01:19) [GCC 7.5.0]
numpy                1.19.5
Pillow               7.1.2
vissl                0.1.5 @/usr/local/lib/python3.7/dist-packages/vissl
GPU available        True
GPU 0                Tesla P100-PCIE-16GB
CUDA_HOME            /usr/local/cuda
torchvision          0.6.1+cu101 @/usr/local/lib/python3.7/dist-packages/torchvision
hydra                1.1.0 @/usr/local/lib/python3.7/dist-packages/hydra
classy_vision        0.6.0.dev @/usr/local/lib/python3.7/dist-packages/classy_vision
tensorboard          1.15.0
apex                 unknown
cv2                  4.1.2
PyTorch              1.9.0+cu102 @/usr/local/lib/python3.7/dist-packages/torch
PyTorch debug build  False
-------------------  ---------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

CPU info:
-------------------  ------------------------------
Architecture         x86_64
CPU op-mode(s)       32-bit, 64-bit
Byte Order           Little Endian
CPU(s)               2
On-line CPU(s) list  0,1
Thread(s) per core   2
Core(s) per socket   1
Socket(s)            1
NUMA node(s)         1
Vendor ID            GenuineIntel
CPU family           6
Model                63
Model name           Intel(R) Xeon(R) CPU @ 2.30GHz
Stepping             0
CPU MHz              2299.998
BogoMIPS             4599.99
Hypervisor vendor    KVM
Virtualization type  full
L1d cache            32K
L1i cache            32K
L2 cache             256K
L3 cache             46080K
NUMA node0 CPU(s)    0,1
-------------------  ------------------------------
```

**Comment by iseessel** [comment]
Hi there sorry your having this issue, we will be revisiting our tutorials soon.  I'm able to reproduce this issue. 

Can you try replacing the installation with: 

```
# installing pytorch and torchvision
!pip install torch==1.7.1+cu101 torchvision==0.8.2+cu101 -f https://download.pytorch.org/whl/torch_stable.html
# installing apex
!pip install -f https://dl.fbaipublicfiles.com/vissl/packaging/apexwheels/py37_cu101_pyt171/download.html apex
# clone vissl repository
!git clone --recursive https://github.com/facebookresearch/vissl.git 
# install vissl dependencies
!pip install --progress-bar off -r requirements.txt
!pip install opencv-python
# update classy vision install to current master
!pip uninstall -y classy_vision
!pip install classy-vision@https://github.com/facebookresearch/ClassyVision/tarball/master

!pip install ".[dev]"

!python -c 'import vissl, apex'
```

Taken from: https://github.com/facebookresearch/vissl/pull/347#issuecomment-870067084

**Comment by rcterrile** [comment]
Hi, thank you for getting back to me.  I replaced the installation and am now getting an error with the line 
```
from vissl.utils.io import save_file
```
The error reads:
```
ModuleNotFoundError: No module named 'vissl.utils'
```
I am not sure if it is related but during the installation there are two errors that show up:
```
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

and

ERROR: Directory '.[dev]' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
```

**Comment by pranavsinghps1** [comment]
Hey @rcterrile ! To navigate this error you need to first move into the installed directory, if you are using Colab you can simply copy the path from the left-hand side panel and then 
``` cd file/path ```
and then use the 
``` !pip install ".[dev]" ```
For reference, you can check out the "Install Vissl" section at https://colab.research.google.com/drive/1KqrvOs5fsu5tbxDF_wNEPJX-OU_RoeG9?usp=sharing#scrollTo=VohdWhBSw69e

**Comment by rcterrile** [comment]
Hi @pranavsinghps1 thank you for the help.  Changing directories solves the .[dev] issue.  However, now I am getting  an error with the following line:
```
print(VisslDatasetCatalog.get("dummy_data_folder"))
```
```
KeyError: 'dummy_data_folder'
```
I tried other names but I could not get it working so far.  Also, thank you for pointing me to the SimCLR notebook, it is quite helpful.

**Comment by pranavsinghps1** [comment]
> Hi @pranavsinghps1 thank you for the help. Changing directories solves the .[dev] issue. However, now I am getting an error with the following line:
> 
> ```
> print(VisslDatasetCatalog.get("dummy_data_folder"))
> ```
> 
> ```
> KeyError: 'dummy_data_folder'
> ```
> 
> I tried other names but I could not get it working so far. Also, thank you for pointing me to the SimCLR notebook, it is quite helpful.

To Solve this:
1. Import the VisslDatasetCatalog file before using the get function as :
``` from vissl.data.dataset_catalog import VisslDatasetCatalog ``` 
2. To print the list of all the available datasets in the catalog as :
``` print(VisslDatasetCatalog.list()) ```
and output would be like:
``` ['airstore_imagenet', 'imagenet1k_folder', 'imagenet_a_filelist', 'imagenet_r_filelist', 'imagenette_160_folder', 'places205_folder', 'places365_folder', 'CIFAR10', 'CIFAR100', 'STL10', 'MNIST',  .... ..... ]``` 
3. You can pick any dataset and pass in the get function! I have used CIFAR 10 as an example 
``` print(VisslDatasetCatalog.get("CIFAR10")) ```
You should  see the output as :
``` {'train': ['<path_to_pytorch_dataset>', '<unused>'], 'val': ['<path_to_pytorch_dataset>', '<unused>']} ```

Hope this helps! Let me know if the issue still persists! :)

**Comment by rcterrile** [comment]
Hi, thank you for the help.  Importing VisslDatasetCatalog was working yesterday for me, but today running 
```
from vissl.data.dataset_catalog import VisslDatasetCatalog
```
results in the following error
```
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
<ipython-input-19-420cdaa8a7cc> in <module>()
----> 1 from vissl.data.dataset_catalog import VisslDatasetCatalog

6 frames
/usr/lib/python3.7/json/decoder.py in decode(self, s, _w)
    338         end = _w(s, end).end()
    339         if end != len(s):
--> 340             raise JSONDecodeError("Extra data", s, end)
    341         return obj
    342 

JSONDecodeError: Extra data: line 167 column 1 (char 5586)
```

Could you please help me with this?

**Comment by pranavsinghps1** [comment]
Hey! You are encountering a JSONDecodeError, which could be because of inappropriate manipulation of the dataset_catalog.json file, can you share which command are you using for appending/editing the dataset_catalog.json file.

**Comment by rcterrile** [comment]
Hey, thanks for getting back to me.  I believe this is the line for the dataset_catalog.json file:
```
json_data = {
    "dummy_data_folder": {
      "train": [
        "/content/dummy_data/train", "/content/dummy_data/train"
      ],
      "val": [
        "/content/dummy_data/val", "/content/dummy_data/val"
      ]
    }
}

# use VISSL's api to save or you can use your custom code.
from vissl.utils.io import save_file
save_file(json_data, "/content/vissl/configs/config/dataset_catalog.json")
```
This is the code given in the "Using the custom data in VISSL" chapter of the "Understanding VISSL Training and YAML Config.ipynb" tutorial notebook.

**Comment by pranavsinghps1** [comment]
Thanks! I was able to reproduce this error, For me, the following worked, To Solve this:
- Delete the vissl/configs/config/dataset_catalog.json file 
- and use ``` save_file(json_data, "/content/vissl/configs/config/dataset_catalog.json", append_to_json=False ) ```
The save_file function in the tutorial is appending outside the JSON string and thereby rendering the file unreadable. 

cc: @iseessel

**Comment by prigoyal** [comment]
thank you @pranavsinghps1 for helping figure out the issue.

@iseessel , I think we should impose some kind of lock / check mechanism on the `dataset_catalog.json` file such that the `save_file` should be saved with `append_to_json=False` automatically or should delete the file before saving again.

**Comment by pranavsinghps1** [comment]
> thank you @pranavsinghps1 for helping figure out the issue.
> 
> @iseessel , I think we should impose some kind of lock / check mechanism on the `dataset_catalog.json` file such that the `save_file` should be saved with `append_to_json=False` automatically or should delete the file before saving again.

From what I can see at https://github.com/facebookresearch/vissl/blob/6b3add3647fef1bfde98fc6a75f51f1e6b835dde/vissl/utils/io.py#L70 we are just opening the file (without loading the JSON object), This works fine when ```append_to_json=False``` or re-writing the file as we end up with one JSON object, but when we append without loading the JSON object, we simply add to the file -- making the file end up with two JSON objects and hence rendering it unreadable.

A possible solution to this could be re-writing https://github.com/facebookresearch/vissl/blob/6b3add3647fef1bfde98fc6a75f51f1e6b835dde/vissl/utils/io.py#L72
So it first loads the JSON object and then appends to it, and then writes the JSON object to the file(Instead of simply appending it to the file). This way even if the JSON file is updated, it will end up with only one object - Appending while still preserving older entries - achieving its original functionality of "appending".

**Comment by rcterrile** [comment]
Thank you for all your help, I have one more quick question regarding datasets with VISSL.  The format is like 
```
train/
      label1/
         image1.jpg
         image2.jpg
         ...
     label2/
        ... more images ...
   val/
      label1/
         image1.jpg
         image2.jpg
         ...
     label2/
        ... more images ...
```
I would just like to clarify that the folders are for labelled data? So label1 and label2 would contain different images?

**Comment by pranavsinghps1** [comment]
Yes, for more information you can check out this tutorial https://vissl.ai/tutorials/Benchmark_Linear_Image_Classification_on_ImageNet_1K#Creating-a-custom-data 
Follow Vissl installation as per https://github.com/facebookresearch/vissl/issues/373#issuecomment-884983189 and https://github.com/facebookresearch/vissl/issues/373#issuecomment-885557969.
Hope this helps!

**Comment by rcterrile** [comment]
Thank you very much.
