### ISSUE TITLE
Hydra 1.1.0 does not override config (wheras 1.0.6 does)

### ISSUE THREAD

**Issue by smn57** [facebookresearch/vissl#384]
I followed installation and starting with simclr guides on my personal computer. When I initialized the environment on a remote machine, some days later, I ran into problems. I tracked it down to hydra, which was updated 5d 9h (as of 11pm on 02.08. GMT+2) from 1.0.6 to 1.1.0 in [anaconda](https://anaconda.org/conda-forge/hydra-core). 
Overrides do not happen and `cfg` stays at default values. 

It worked on my local machine (initialized 27.07.). Today (02.08.) I updated hydra (only this package) manually to 1.1.0 and ran into the same problem as on my remote server.

## Instructions To Reproduce the 🐛 Bug:
1. print cfg after L172 in `run_distributed_engines.py` following [your tutorial](https://vissl.ai/tutorials/Train_SimCLR_on_1_gpu#Train)

## Expected behavior:
Updated cfg, i.e. `'NUM_PROC_PER_NODE': 1` and NOT `'NUM_PROC_PER_NODE': 8` (which is set as default).

## Environment:
```
PyTorch version: 1.7.1
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-6ubuntu2) 7.5.0
Clang version: Could not collect
CMake version: version 3.16.3

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
***

Nvidia driver version: 460.91.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] torch==1.7.1
[pip3] torchvision==0.8.2
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.2.89              hfd86e86_1  
[conda] faiss-gpu                 1.7.1           py3.8_h080d439_1_cuda10.2    pytorch
[conda] libfaiss                  1.7.1           h4fe19ad_1_cuda10.2    pytorch
[conda] mkl                       2021.3.0           h06a4308_520  
[conda] mkl-service               2.4.0            py38h7f8727e_0  
[conda] mkl_fft                   1.3.0            py38h42c9631_2  
[conda] mkl_random                1.2.2            py38h51133e4_0  
[conda] numpy                     1.20.3           py38hf144106_0  
[conda] numpy-base                1.20.3           py38h74d4b33_0  
[conda] pytorch                   1.7.1           py3.8_cuda10.2.89_cudnn7.6.5_0    pytorch
[conda] torchvision               0.8.2                py38_cu102    pytorch
```

**Comment by prigoyal** [comment]
cc @QuentinDuval who's looking at Hydra 1.1

**Comment by QuentinDuval** [comment]
Hi @smn57,

First of all thank you for using VISSL and raising the issue!

The short answer is VISSL does not yet support Hydra 1.1 (but it is coming !).

The longer reason is that Hydra 1.1 introduces non backward compatible change with Hydra 1.0.6 regarding the defaults list, and this requires some changes on VISSL as well as other Hydra client code.

In the meantime, you can use Hydra 1.0.6 or Hydra 1.0.7.

Sorry again for the inconvenience :/

**Comment by smn57** [comment]
Thank you for validating my assumption!

**Comment by QuentinDuval** [comment]
Closing the issue (Hydra 1.1 will be coming through another issue)
