### ISSUE TITLE
How to get image names from idx of features extracted?

### ISSUE THREAD

**Issue by DC95** [facebookresearch/vissl#401]
## ❓ How to get names of images from idx of features extracted?

Dear @QuentinDuval 

**Introduction -** 
For evaluation of the Deepcluster_V2 model, I have tried the [benchmark of KNN ](https://vissl.readthedocs.io/en/latest/evaluations/nearest_neighbor.html) to analyze few samples from the test images which belong nearest to the train images. 
Since I am not operating on labelled or class dataset (top1 or top5 is irreleveant here). Therefore I am interested in collecting the top - k neighbours which I think is up to line 70 of [nearest_neighbour_test.py](https://github.com/facebookresearch/vissl/blob/master/tools/nearest_neighbor_test.py#L70)

**Output -** 
The variable "retreived_neighbours" from nearest_neighbour_test.py gives k indices of the train image set nearest to the test image. 

1. for example top 5 neighbours for a test image - 
    tensor([[    2,   228, 11803, 13161,     1],], device='cuda:0')

**Question -** 
But I am not able to figure out how to get the image names from this?

**Please note -** 
I followed the answer of @prigoyal from #340. But could not understand or relate much 

regards,
DC

**Comment by QuentinDuval** [comment]
Hi @DC95,

The indices should correspond to the indices of the dataset, which means that you should be able to get the images like this: `dataset[index]`. This is used in the context of Cluster Fit if applied on an image folder.

One way to do this would be to use the function "get_image_paths": https://github.com/facebookresearch/vissl/blob/master/tools/cluster_features_and_label.py#L50

```
image_paths = get_image_paths(config, split="train")
for idx in [2, 228, 11803, 13161, 1]:
    print(image_paths[idx])
```

Could you tell me if that works for you? If so, we can make this function more easily available.

And thank you again @DC95 for using VISSL :)
Quentin

**Comment by DC95** [comment]
Dear @QuentinDuval 

Thanks for the idea. Yes, it worked. We need to bring some more changes in the [nearest_neighbour_test.py](https://github.com/facebookresearch/vissl/blob/master/tools/nearest_neighbor_test.py) to get it done.

1. `from vissl.data import build_dataset` 
2. under the main function after line 124 call the get_image_paths function 
```
image_paths = get_image_paths(config, split="TRAIN")
for idx in [2, 228, 11803, 13161, 1]:   # as thrown by retrieved neighbour variable.
    print(image_paths[idx])
```

Thanks again, and I will keep knocking on the issue door in the future. 

Regards,
DC

**Comment by QuentinDuval** [comment]
Hi @DC95,

Excellent, I am very glad it worked :)

CC: @prigoyal, @iseessel : I think we can make that simpler on our side and add some utilities to do so.

Closing the issue.

**Comment by iseessel** [comment]
Something like the following should work: 

```
    def __getitem__(self, idx: int):
        """
        Get the input sample for the minibatch for a specified data index.
        For each data object (if we are loading several datasets in a minibatch),
        we get the sample: consisting of {
            - image data,
            - label (if applicable) otherwise idx
            - data_valid: 0 or 1 indicating if the data is valid image
            - data_idx : index of the data in the dataset for book-keeping and debugging
        }
        Once the sample data is available, we apply the data transform on the sample.
        The final transformed sample is returned to be added into the minibatch.
        """

        if not self._labels_init and len(self.label_sources) > 0:
            self._load_labels()
            self._labels_init = True
         
         from vissl.utils.io import save_file
         save_file(self.label_paths(), "/path/to/labels.json")
```
