### ISSUE TITLE
How to get names of images from idx of indexes_all in DC_V2?

### ISSUE THREAD

**Issue by DC95** [facebookresearch/vissl#423]
## ❓How to get names of images from IDX of indexes_all in DC_V2?
Dear @iseessel, @QuentinDuval 

**Introduction -**

Since the deepclusterv2_loss.py uses only [loss_config](https://github.com/facebookresearch/vissl/blob/master/vissl/losses/deepclusterv2_loss.py#L84) therefore I cannot use what is suggested in #401. #401 uses other pieces of information from the main_config, for example, such as self.data_sources 

I understand DC_v2_loss.py does not require the rest of the config information for loss calculation.

**What have I done and understand -** 

1. For evaluation of the clusters, I have dumped  [assignments ](https://github.com/facebookresearch/vissl/blob/master/vissl/losses/deepclusterv2_loss.py#L203) and all index values corresponding to assignments. (example attached
![assignments_indexes](https://user-images.githubusercontent.com/57698337/133582706-641691c2-e70a-4aaa-b454-53a508227d31.png)
)
2. For data loading, I see [dataloader](https://github.com/facebookresearch/vissl/blob/master/vissl/losses/deepclusterv2_loss.py#L112) is used here, **_but I don't know how to get image names from the data loader**_

**Question -** 

1. Can somehow all the configurations be called so that I can use what is suggested in #401 

Cheers,
DC

**Comment by iseessel** [comment]
Hi there @DC95 -- I do agree it would be hard to extract the image names for the clusters while they are training. 

However, it is easy to do so after the fact. You can use https://github.com/facebookresearch/vissl/issues/401 to save the image_paths, e.g. after this is called: https://github.com/facebookresearch/vissl/blob/87ef9a19c193dc91add9dd56bee1b9b701693672/vissl/data/ssl_dataset.py#L313

Then you can match the index of this array to the index that you have in indeces.

**Comment by DC95** [comment]
I have images in a folder (Train and Test separate) and I register them in dataset_catalog.json. So I think it's the Disk folder.

**Comment by iseessel** [comment]
Got it -- then the above should work -- let me know if I'm not being clear!

**Comment by DC95** [comment]
Dear @iseessel,

As suggested by you, I looked into the [file](https://github.com/facebookresearch/vissl/blob/87ef9a19c193dc91add9dd56bee1b9b701693672/vissl/data/ssl_dataset.py#L313). But I have some questions- 

- What I understood is that self._load_labels() (line 313) is meant for loading labels (if the dataset has one).

- But maybe I didn't tell you before - 

1. I have unlabelled satellite images. I have applied DC_v2, and now I have the cluster ids and corresponding image indices. But I want to get the image file names.

Can you kindly tell me once more how to proceed with the solution? Maybe I misunderstood you.

**Comment by iseessel** [comment]
Something like the following should work: 

```
    def __getitem__(self, idx: int):
        """
        Get the input sample for the minibatch for a specified data index.
        For each data object (if we are loading several datasets in a minibatch),
        we get the sample: consisting of {
            - image data,
            - label (if applicable) otherwise idx
            - data_valid: 0 or 1 indicating if the data is valid image
            - data_idx : index of the data in the dataset for book-keeping and debugging
        }
        Once the sample data is available, we apply the data transform on the sample.
        The final transformed sample is returned to be added into the minibatch.
        """

        if not self._labels_init and len(self.label_sources) > 0:
            self._load_labels()
            self._labels_init = True
         
         from vissl.utils.io import save_file
         save_file(self.label_paths(), "/path/to/labels.json")
```

This file loads the images and optionally the labels if you have them.

**Comment by DC95** [comment]
Thanks, let me try :)

**Comment by DC95** [comment]
Dear @iseessel 

I am sorry to report but,

I have tried both- 
`save_file(self.label_paths, "/path/to/label_path.txt")` (txt file attached)
and
`save_file(self.data_paths, "/path/to/data_path.txt")` (txt file attached)

with self.label_paths it's coming as an empty list and more lists than no. of training files.

**Kind note** - If I use self.label_paths **()** then it's giving TypeError: 'list' object is not callable, that's why I removed the brackets.

[data_path.txt](https://github.com/facebookresearch/vissl/files/7197828/data_path.txt)
[label_path.txt](https://github.com/facebookresearch/vissl/files/7197829/label_path.txt)

**Comment by iseessel** [comment]
Sorry I had a typo in my original. Can you try something like: 

```
    def __getitem__(self, idx: int):
        """
        Get the input sample for the minibatch for a specified data index.
        For each data object (if we are loading several datasets in a minibatch),
        we get the sample: consisting of {
            - image data,
            - label (if applicable) otherwise idx
            - data_valid: 0 or 1 indicating if the data is valid image
            - data_idx : index of the data in the dataset for book-keeping and debugging
        }
        Once the sample data is available, we apply the data transform on the sample.
        The final transformed sample is returned to be added into the minibatch.
        """

        if not self._labels_init and len(self.label_sources) > 0:
            self._load_labels()
            self._labels_init = True
         
         from vissl.utils.io import save_file
         save_file(self.get_image_paths(), "/path/to/labels.json")
```

**Comment by DC95** [comment]
Dear @iseessel 

I followed your suggestion but - 

1. In disk_dataset.py, line [139](https://github.com/facebookresearch/vissl/blob/87ef9a19c193dc91add9dd56bee1b9b701693672/vissl/data/disk_dataset.py#L139)-
`image_path = self.image_dataset[idx]` has information like - _(<PIL.Image.Image image mode=RGB size=128x128 at 0x2B69DB5866A0>, 0)_ for each image but this does not contain information like I thought.

2. One more thing interesting is that I looked at the IDX values getting called in [def __getitem__() ](https://github.com/facebookresearch/vissl/blob/87ef9a19c193dc91add9dd56bee1b9b701693672/vissl/data/disk_dataset.py#L122) of disk_dataset.py. It is storing IDX values almost twice the number of training size, each IDX is twice present there.  

3. In ssl_dataset.py  by saving self.get_image_paths(), like suggested by you `save_file(self.get_image_paths(), "/path/to/labels.json")`, keeps on running the program infinitely.

4. What I observed that [def get_image_paths(self):](https://github.com/facebookresearch/vissl/blob/87ef9a19c193dc91add9dd56bee1b9b701693672/vissl/data/ssl_dataset.py#L378) from ssl_dataset has the information of datapaths but not in the order in which they are being called.

Regards,
DC

**Comment by iseessel** [comment]
@DC95 Can you post the config you are training + your dataset catalog + the code you are using to save the cluster assignments + indexes above. 

#2 -> Can you be more specific. What do you mean by this? 

#3 -> You need to call this only once. You can use something like self.saved_results

#4 -> Yes that is correct. I would recommend saving the assignment indexes, not in the order in which they are called, but instead based on inputs["data_idx"]. e.g. here: https://github.com/facebookresearch/vissl/blob/master/vissl/losses/deepclusterv2_loss.py#L117

**Comment by DC95** [comment]
Hi @iseessel,

I am posting the files asked by you

- JSON file, YAML file, .py file can't be uploaded here that's why I am attaching in txt format.
- I am doing some changes in the deep cluster_v2 loss to have the assignment and the indexes dumped.
Like in deepclusterv2_loss.py changed part is shown like this - 
```
#################################
changed code
################################## 
```
-  can't be posted here so attaching txt version

More explanation about point 2 from above post - 
If I save the idx values from for a run of only 1 epoch- 
`image_path = self.image_dataset[idx]
 save_file(idx,"/p/project/deepacf/kiste/DC/juelich_2x85_128x128_15k/checkpoints_train_400ep_exp/disk_dataset_getitem_idx1.json")`

Then let's say I have a training image dataset of 15077 I am getting more than 15077 idx values 


[dcv2_2x85_rnet_128x128_Juelich.txt](https://github.com/facebookresearch/vissl/files/7206105/dcv2_2x85_rnet_128x128_Juelich.txt)
[deepclusterv2_loss.txt](https://github.com/facebookresearch/vissl/files/7206191/deepclusterv2_loss.txt)
[dataset_catalog.txt](https://github.com/facebookresearch/vissl/files/7206001/dataset_catalog.txt)

Regards,
DC
.

**Comment by iseessel** [comment]
Thanks for the info @DC95!

I was able to get my hands dirty and this is what I found that works -- check this commit: https://github.com/iseessel/vissl/commit/da35a50113feb16884e9a87d72e4ebb27a4bd75d

The indexes of `samples.npy` should match the indexes of the assignments. 

Re:

```
One more thing interesting is that I looked at the IDX values getting called in def getitem() of disk_dataset.py. It is storing IDX values almost twice the number of training size, each IDX is twice present there.
```

This should not be happening and I was unable to repro it with a test dataset of 100 train and test images. For this: 

1.  Can you please verify the number of images in your folder: `/p/project/deepacf/kiste/DC/dataset/hope2013_128x128_image/train_juelich_128x128_15k`. 
2. Can you run your config with my above commit and verify the indexes are indeed above what's expected.
3. If 1/2 still fail, can you send the output of `samples.npy`.

**Comment by DC95** [comment]
Dear @iseessel 

Thanks for jumping into the mud. I agree that the commit works nicely specially the line`save_file(self.image_dataset.samples, "/private/home/iseessel/samples.npy")` . 
I am attaching the output `sample. npy` in zip

[samples.zip](https://github.com/facebookresearch/vissl/files/7220170/samples.zip)

I have one thing to ask - 
- if I see the positional order in which images names are present in sample .npy. Do they correspond to the same index order appearing in indexes_all from deepcluster_v2?
- I think the answer is yes, but just asking.

I will send more analysis of this by tomorrow or Monday.

I am also attaching the `assignment and indexes` in zip.
[assignment_indexes.zip](https://github.com/facebookresearch/vissl/files/7220407/assignment_indexes.zip)
.

**Comment by iseessel** [comment]
Yep you are right -- they do match!

**Comment by DC95** [comment]
Well, then the journey of finding image_names, indexes, and assignments comes to an end, I see. Thanks, @iseessel, very much for the constant support. 

Cheers,
DC

**Comment by iseessel** [comment]
feel free to open back up if any probs!
