### ISSUE TITLE
Can this repo be used to reproduce transfer learning performances detailed in SimCLR, BYOL and NNCLR?

### ISSUE THREAD

**Issue by yxchng** [facebookresearch/vissl#432]
It seems like this repo can reproduce transfer learning results in MoCo, SwAV, SimSiam, Barlow Twins and VICReg but has large gap compared to those done in SimCLR, BYOL and NNCLR.

This figure details results aligned with those published in SimCLR, BYOL and NNCLR papers (taken from NNLCR paper):
<img width="1237" alt="Screenshot 2021-10-03 at 1 00 45 AM" src="https://user-images.githubusercontent.com/10518587/135726145-8390924a-e961-43e9-aa7a-62df47b211e7.png">

This figure details results aligned with those published in MoCo, SwAV, SimSiam, Barlow Twins and VICReg (taken from VICReg paper):
<img width="571" alt="Screenshot 2021-10-03 at 1 00 33 AM" src="https://user-images.githubusercontent.com/10518587/135726151-3030aef5-dceb-42e5-8c7e-d531830ab579.png">

Notice that for VOC07, the results in the second figure are much higher than that of the first figure. From what I understood, the results for SimCLR and BYOL in the second figure are reproduced by subsequent authors using different protocols from that used by the original authors (but similar to that done in vissl).

Based on the figures linked in this commit message, https://github.com/facebookresearch/vissl/commit/395435a3460e9ef1328a76c1ebaa8011fb98e390, results for SimCLR on other datasets like Caltech, Pets and DTD are also quite a bit lower than published by the original SimCLR authors in the first figure above.

So my question is can this repo reproduce transfer learning results in figure 1 above? If not, are there plans to support doing so in the future? Thanks.

**Comment by prigoyal** [comment]
Hi @yxchng , thank you for reaching out. The short answer to your question is yes. Note that the benchmarks on caltech, pets etc are new and every paper uses different hyperparams of their own. In VISSL, we repro numbers on Caltech, food, dtd etc and match them for RN50 model (for instance) with the CLIP https://arxiv.org/pdf/2103.00020.pdf and VTAB https://arxiv.org/pdf/1910.04867.pdf benchmarks. We recommend that the model that you are interested in, you can consult the respective papers and use the exact same hyperparams as they recommend. 

Also for SwAV and PIRL, we reproduce all the numbers. For MoCOv2 and Barlow Twins, we report our IN1K linear (we didn't try the other benchmarks but you are welcome to use the model weights and eval on Places, inat etc other benchmarks). Hope this helps.

**Comment by yxchng** [comment]
How do I do 11-point MAP in VOC07? This is done in the first figure, aside from using different train-val split.

**Comment by iseessel** [comment]
Let me know if I should re-open this, but I'm going to close for now. @yxchng
