### ISSUE TITLE
Update default Binaries

### ISSUE THREAD

**Issue by amitbcp** [facebookresearch/vissl#435]
Hi Team, 

It seems the last pre-built binary was cut in March and since then a lot of things have been added and fixed in the repo. Maybe we can have a new pre-built binary.

Also all the installation doc says to used Cuda 10, any particular reason or should it work smoothly for coda 11 its respective pytorch version ?

**Comment by prigoyal** [comment]
Hi @amitbcp , thank you! 
- yes, @iseessel is driving the work on upgrading the packages.
- it should work with CUDA 11. Please let us know if you encounter any issues.

**Comment by iseessel** [comment]
Hi @amitbcp yes we should support all versions of cuda that are compatible with pytorch. Note that we do not yet fully support Pytorch 1.8.1, 1.9.0, or 1.9.1. 

Support for these should be coming early next week at the latest. A new minor release of vissl, accompanied by new prebuilt binaries should be coming by the end of this month.

**Comment by iseessel** [comment]
Hi @amitbcp we have released a new version of VISSL.

See our release notes for how to update: https://github.com/facebookresearch/vissl/releases/tag/v0.1.6.
