### ISSUE TITLE
ClusterFit model: cluster_features_resnet_8gpu_rotation_in1k missing

### ISSUE THREAD

**Issue by rgeirhos** [facebookresearch/vissl#452]
## 📚 VISSL Documentation

In the documentation for training ClusterFit (https://vissl.readthedocs.io/en/v0.1.5/ssl_approaches/clusterfit.html?highlight=clustering#how-to-train-clusterfit-model), step 1 ("Extract features") requires the following config file: config=pretrain/clusterfit/cluster_features_resnet_8gpu_rotation_in1k. However, there is no such file at https://github.com/facebookresearch/vissl/tree/main/configs/config/pretrain/clusterfit. This might require either adding the file, or updating the documentation in case the file got renamed.

**Comment by rgeirhos** [comment]
Hi @QuentinDuval, thanks for your fast & helpful reply!

 From my side, please feel free to either close this issue or leave it open until the docs are updated :)

**Comment by kulkarnivishal** [comment]
What's CHUNCK_THRESHOLD?
