### ISSUE TITLE
Facing RuntimeError: with nearest_neighbour_test.py

### ISSUE THREAD

**Issue by DC95** [facebookresearch/vissl#519]
Hii VISSL team!!

## **Introduction -** 
I have earlier used KNN from the VISSL package, for example, you can see one issue that I raised in the past [Link](https://github.com/facebookresearch/vissl/issues/401)

## **My target -** 
is again the same to get K nearest neighbors to the test image

## **Error -** 
For the last few days, I am trying to use [nearest_neighbor_test.py](https://github.com/facebookresearch/vissl/blob/main/tools/nearest_neighbor_test.py) but it is throwing me this error - 
```
_RuntimeError: CUDA error: device-side assert triggered
terminate called after throwing an instance of 'std::runtime_error'
  what():  NCCL error in: ../torch/lib/c10d/../c10d/NCCLUtils.hpp:155, unhandled cuda error, NCCL version 21.0.3
ncclUnhandledCudaError: Call to CUDA function failed.
Aborted_
```
I have checked with both the Main branch and v0.1.6 but the same results. 

## **Interesting observation -** 
is that Model training is working fine but only with running KNN, it is throwing this error.

## **Additional information -** 
I work in an HPC environment

## **Environment**:
-------------------  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
`sys.platform         linux
Python               3.8.5 (default, Sep 13 2021, 15:26:00) [GCC 10.3.0]
numpy                1.19.5
Pillow               7.0.0.post3
vissl                0.1.5 @/p/project/deepacf/kiste/DC/vissl_b/vissl
GPU available        True
GPU 0                NVIDIA A100-SXM4-40GB
CUDA_HOME            /p/software/juwelsbooster/stages/2020/software/CUDA/11.3
torchvision          0.9.0a0 @/p/software/juwelsbooster/stages/2020/software/torchvision/0.9.1-gcccoremkl-10.3.0-2021.2.0-Python-3.8.5/lib/python3.8/site-packages/torchvision-0.9.0a0-py3.8-linux-x86_64.egg/torchvision
hydra                1.0.7 @/p/project/deepacf/kiste/DC/vissl_booster/venv/lib/python3.8/site-packages/hydra
classy_vision        0.6.0.dev @/p/home/jusers/chatterjee1/juwels/.local/lib/python3.8/site-packages/classy_vision
tensorboard          2.5.0
apex                 0.1 @/p/home/jusers/chatterjee1/juwels/.local/lib/python3.8/site-packages/apex
cv2                  4.5.2
PyTorch              1.8.1 @/p/software/juwelsbooster/stages/2020/software/PyTorch/1.8.1-gcccoremkl-10.3.0-2021.2.0-Python-3.8.5/lib/python3.8/site-packages/torch
PyTorch debug build  False
-------------------  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 10.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.2-Product Build 20210312 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash N/A)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_72,code=sm_72;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.2.1
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.1, CXX_COMPILER=/p/software/juwelsbooster/stages/2020/software/GCCcore/10.3.0/bin/g++, CXX_FLAGS=-O2 -ftree-vectorize -march=native -fno-math-errno -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.1, USE_CUDA=1, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

CPU info:
-------------------------------  -----------------------------------------------------------------------------------------
Architecture                     x86_64
CPU op-mode(s)                   32-bit, 64-bit
Byte Order                       Little Endian
Address sizes                    43 bits physical, 48 bits virtual
CPU(s)                           96
On-line CPU(s) list              0-95
Thread(s) per core               2
Core(s) per socket               24
Socket(s)                        2
NUMA node(s)                     8
Vendor ID                        AuthenticAMD
CPU family                       23
Model                            49
Model name                       AMD EPYC 7402 24-Core Processor
Stepping                         0
Frequency boost                  enabled
CPU MHz                          2800.000
CPU max MHz                      2800.0000
CPU min MHz                      1500.0000
BogoMIPS                         5599.90
Virtualization                   AMD-V
L1d cache                        1.5 MiB
L1i cache                        1.5 MiB
L2 cache                         24 MiB
L3 cache                         256 MiB
NUMA node0 CPU(s)                0-5,48-53
NUMA node1 CPU(s)                6-11,54-59
NUMA node2 CPU(s)                12-17,60-65
NUMA node3 CPU(s)                18-23,66-71
NUMA node4 CPU(s)                24-29,72-77
NUMA node5 CPU(s)                30-35,78-83
NUMA node6 CPU(s)                36-41,84-89
NUMA node7 CPU(s)                42-47,90-95
Vulnerability Itlb multihit      Not affected
Vulnerability L1tf               Not affected
Vulnerability Mds                Not affected
Vulnerability Meltdown           Not affected
Vulnerability Spec store bypass  Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1         Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2         Mitigation; Full AMD retpoline, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling
Vulnerability Srbds              Not affected
Vulnerability Tsx async abort    Not affected

Kindly help!!

Warm regards,
DC
`

**Comment by DC95** [comment]
# I have cross-checked with both branches 
vissl -  `0.1.5 @/p/project/deepacf/kiste/DC/vissl_b/vissl` **and** `0.1.6 @/p/project/deepacf/kiste/DC/vissl_b2/vissl`

# Attached are files for reference - 
Log.txt file on running KNN [log.txt](https://github.com/facebookresearch/vissl/files/8081137/log.txt)
Yaml_config_[link](https://drive.google.com/file/d/17MHifz1A7jM8S3FD8wGHiXtXxM_-9-Ol/view?usp=sharing)

Warm regards,
DC
`

**Comment by QuentinDuval** [comment]
Hi @DC95,

Interesting. We may have broken some things on the [nearest_neighbor_test.py](https://github.com/facebookresearch/vissl/blob/main/tools/nearest_neighbor_test.py) (although it is covered by tests, this is by no means a perfect way to catch all bugs).

Could you send me the complete command that you are using to run KNN?
(to complete the configuration you already sent)

I will have a look.

Thank you,
Quentin

**Comment by QuentinDuval** [comment]
Hi @DC95,

Nice to talk to you again as well :)

I will try to reproduce that and keep you posted.

And thanks again for the bug report, this is really super helpful for us 👍

**Comment by QuentinDuval** [comment]
Hi @DC95,

I could not find any issue with your configuration and could run the KNN properly. The issue I found was instead in the command line. You should use `tools/nearest_neighbor_test.py` instead of `run_distributed_engine.py`.

Like so:

```
python ~/project/ssl_scaling/tools/nearest_neighbor_test.py config=test/temp/dcv2_96x2_128x128_germany
```

Tell me if this works better now !

**Comment by DC95** [comment]
Hi @QuentinDuval 

I am really sorry for the confusion. I am a bit ashamed of myself about this. How could I miss this minor detail? 

- It works all well now

I was looking everywhere for the answers—a Big thanks to you. We should close this issue.

Regards,
DC

**Comment by QuentinDuval** [comment]
Hi @DC95,

Don't worry, that happens to everyone :) To be fair, I found it quickly because it happened to me ^^

Closing the issue !

Thank you,
Quentin
