### ISSUE TITLE
Broken Links and expired url signatures in the Fairness Indicators README

### ISSUE THREAD

**Issue by tbarton16** [facebookresearch/vissl#536]
## 📚 VISSL Documentation

Hello, there are some Broken Links and expired url signatures in the Fairness Indicators [README](https://github.com/facebookresearch/vissl/blob/main/projects/fairness_indicators/label_associations_indicator1.md
). 
Here they are:

  "- __[Inference] Setup of Casual Conversations (CC)__: Following the [CC dataset guidelines](https://ai.facebook.com/datasets/casual-conversations-dataset/), obtain access to the dataset. We setup the _mini-test_ split of the dataset which has 2982 videos. We follow the [CC paper Section 4.1](https://scontent-iad3-2.xx.fbcdn.net/v/t39.8562-6/10000000_1032795703933429_5521369258245261270_n.pdf?_nc_cat=111&ccb=1-5&_nc_sid=ae5e01&_nc_ohc=_S3fHxQzy6sAX9C7nMJ&_nc_ht=scontent-iad3-2.xx&oh=00_AT-wqHBSuj1fqg4yn8hK4U_ar57IUOjSQ776fiLGu_2FWw&oe=6208F25B) for inference on face crops. Please refer to our research [Appendix B.1](**TODO**) for further details. We parse the dataset to generate a single _.json_ file with the format:" 

I can fix these if you want.

**Comment by QuentinDuval** [comment]
Hi @tbarton16,

Thanks a lot for your interest in VISSL and good catch indeed!

If you want to fix these, please do :)
I would be glad to review your pull request !

Thank you,
Quentin
